version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2
jobs:
  build:
    executor:
      name: node/default
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test test/TestWithoutPageObject.js
      - slack/status:
          fail_only: false
          webhook: ${SLACK_WEBHOOK}
          message: Hey we have got you the result for your recent build!, here it goes.
          mentions: 'U016NEX0STC'
workflows:
    build:
      jobs:
        - build